services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: pswrd
      MONGO_INITDB_DATABASE: d0007
    restart: unless-stopped

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    restart: unless-stopped