version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOPPLER_TOKEN_BUILD=${DOPPLER_TOKEN_BUILD}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_OAUTH_CALLBACK_URI
      - GOOGLE_SERVICE_ACCOUNT
      - ORIGIN
      - REDIS_URL
      - PUBLIC_BASE_URL
    restart: always
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      - ./devops/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=superadmin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_DATABASE_USERNAME=${MONGO_DATABASE_USERNAME}
      - MONGO_DATABASE_PASSWORD=${MONGO_DATABASE_PASSWORD}
    restart: always

  redis:
    image: redis:7.0-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_persist:/data
    restart: always

  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./devops/nginx/templates:/etc/nginx/templates
    restart: always
 
volumes:
  mongodb:
  mongodb_config:
  redis_persist: